plugins {
    id 'java'
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'me.modmuss50.mod-publish-plugin'
}

base {
    archivesName = "${project.mod_id}-${project.name}-${project.minecraft_version}"
}

group = project.group
version = project.mod_version

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jspecify:jspecify:1.0.0")
    implementation "com.demonwav.mcdev:annotations:2.1.0"
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
['apiElements', 'runtimeElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${project.name}:$version")
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : project.mod_name,
                'Specification-Vendor'  : project.mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : project.mod_author,
                'Built-On-Minecraft'    : project.minecraft_version
        ])
    }
}

processResources {
    def expandProps = [
            "version"                      : project.version,
            "group"                        : project.group, //Else we target the task's group.
            "minecraft_version"            : project.minecraft_version,
            "minecraft_version_range"      : project.minecraft_version_range,
            "forge_version"                : project.forge_version,
            "forge_loader_version_range"   : project.forge_loader_version_range,
            "forge_version_range"          : project.forge_version_range,
            "fabric_api_version"           : project.fabric_api_version,
            "fabric_loader_version"        : project.fabric_loader_version,
            "fabric_version_range"         : project.fabric_version_range,
            "neoforge_version"             : project.neoforge_version,
            "neoforge_loader_version_range": project.neoforge_loader_version_range,
            "neoforge_version_range"       : project.neoforge_version_range,
            "mod_name"                     : project.mod_name,
            "mod_author"                   : project.mod_author,
            "mod_id"                       : project.mod_id,
            "mod_description"              : project.mod_description,
            "license"                      : project.license,
            "repoURL"                      : project.repoURL,
            "issueTrackerURL"              : project.issueTrackerURL,
            "credits"                      : project.credits,
            "java_version"                 : project.java_version
    ]

    var jsonExpandProps = expandProps.collectEntries {
        key, value -> [(key): value instanceof String ? value.replace("\n", "\\\\n") : value]
    }

    filesMatching(['META-INF/mods.toml', 'META-INF/neoforge.mods.toml']) {
        expand expandProps
    }

    filesMatching(['pack.mcmeta', 'fabric.mod.json', '*.mixins.json']) {
        expand jsonExpandProps
    }

    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url = System.getenv('local_maven_url')
        }
    }
}

tasks.register('latestChangelog') {
    group = "changelog"

    def fullChangelog = projectDir.toPath().getParent().resolve("CHANGELOG.md").toFile()
    def latestChangelog = projectDir.toPath().getParent().resolve("LATEST_CHANGELOG.md").toFile()

    int firstHeading = fullChangelog.getText().indexOf("## [")
    int nextHeading = fullChangelog.getText().indexOf("## [", firstHeading + 1)

    String latestChangelogText = fullChangelog.getText().substring(firstHeading, nextHeading)

    outputs.upToDateWhen {
        if (latestChangelog.exists()) {
            return latestChangelogText == latestChangelog.getText()
        } else return false
    }

    outputs.file file("LATEST_CHANGELOG.md")
    doLast {
        latestChangelog.text = latestChangelogText
        printf(latestChangelog.text)
    }
}

publishMods {
    dryRun = false
    type = STABLE
    changelog = project.getRootDir().toPath().resolve("LATEST_CHANGELOG.md").getText()
}

idea.module { downloadJavadoc = downloadSources = true }

tasks.register('publishAll') {
    group = "upload"

    dependsOn("latestChangelog")
    dependsOn("publishMods")
}
