# Gradle
org.gradle.jvmargs=-Xmx4G -Dhttps.protocols=TLSv1.2 -Djdk.tls.client.protocols=TLSv1.2
org.gradle.parallel=true
org.gradle.configuration-cache=false
net.minecraftforge.gradle.merge-source-sets=true
enabled_platforms=neoforge

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_version=2024.11.17
parchment_minecraft=1.21.1

# Project
license=MIT
credits=xiwanzi
repoURL=https://github.com/xiwanzi/OtherworldInnHud
issueTrackerURL=https://github.com/xiwanzi/OtherworldInnHud/issues

# Mod options
mod_version=0.1.0
mod_id=otherworldinn_hud
mod_group=com.xiwanzi
mod_name=Otherworld Inn HUD
mod_author=xiwanzi
mod_description=Otherworld Inn HUD displays seasonal information on the HUD for the Otherworld Inn modpack.

# Minecraft properties
minecraft_version=1.21.1
minecraft_version_range=[1.21, 1.21.2)
java_version=21

# Curseforge/Modrinth
modrinth_forge_id=VNjUn3NA
modrinth_fabric_id=iDiIfZLX
modrinth_gameVersions=1.21,1.21.1
curseforge_forge_id=690971
curseforge_fabric_id=848022
curseforge_gameVersions=1.21,1.21.1

# Forge properties
# https://files.minecraftforge.net/net/minecraftforge/forge/index_1.21.1.html
forge_version=1.21.1-52.1.14
forge_version_range=[51,)
forge_loader_version_range=[51,)

# Fabric properties
# https://fabricmc.net/develop/
fabric_loader_version=0.19.2
fabric_api_version=0.116.12+1.21.1
fabric_version_range=>=1.21 <=1.21.1

# Neoforge properties
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.1.230
neoforge_version_range=[21.0,)
neoforge_loader_version_range=[4,)

# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430

# Mixins
mixin_version=0.8.5
mixin_extras_version=0.5.0

# ForgeConfigApiPort properties
# https://modrinth.com/mod/forge-config-api-port/versions?g=1.21.1&l=fabric
forge_config_api_port_version=21.1.6

# Season Mods
# https://modrinth.com/mod/serene-seasons/versions?g=1.21.1&l=forge
# https://modrinth.com/mod/glitchcore/versions?g=1.21.1&l=forge
# https://modrinth.com/mod/fabric-seasons/versions?g=1.21.1&l=fabric
# https://modrinth.com/mod/fabric-seasons-extras/versions?g=1.21.1&l=fabric
# https://modrinth.com/mod/terrafirmacraft/versions?g=1.21.1&l=neoforge
# https://modrinth.com/mod/patchouli/versions?g=1.21.1&l=neoforge
# https://modrinth.com/mod/barrels-2012/versions?g=1.21.1&l=neoforge
# https://www.curseforge.com/minecraft/mc-mods/ecliptic-seasons/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6
serene_seasons_version=1.21.1-10.1.0.3
glitchcore_version=1.21.1-2.1.0.0
fabric_seasons_version=2.4.2-BETA+1.21
fabric_seasons_extras_version=1.3.2-BETA+1.21
terrafirmacraft_version=4.1.2
patchouli_version=1.21.1-93-neoforge
barrels_version=2.1
ecliptic_seasons_version=7595115
homeostatic_seasons_version=1.1.0.4
homeostatic_seasons_mc_version=1.21.1
whitenoise_version=2.0.7
climatesettings_version=1.2.0
protomanlys_version=0.16.4-alpha

# Minimaps - Common
# https://modrinth.com/mod/xaeros-minimap/versions?g=1.21.1&l=neoforge&l=fabric
# https://modrinth.com/mod/journeymap/versions?g=1.21.1&l=neoforge&l=fabric
# https://github.com/TeamJM/journeymap-api/tree/1.21.1_2.0_SNAPSHOTS
# https://modrinth.com/mod/common-network/versions?g=1.21.1&l=neoforge&l=fabric
# https://modrinth.com/mod/architectury-api/versions?g=1.21.1&l=neoforge&l=fabric
# https://modrinth.com/mod/map-atlases-forge/versions?g=1.21.1&g=1.21.1&l=neoforge
# https://modrinth.com/mod/map-atlases/versions?g=1.21.1&g=1.21.1&l=fabric
# https://modrinth.com/mod/moonlight/versions?g=1.21.1&l=forge&l=fabric
# https://modrinth.com/mod/immediatelyfast/versions?g=1.21.1&g=1.21.1&l=neoforge&l=fabric
# https://www.curseforge.com/minecraft/mc-mods/ftb-chunks-fabric/files/all?page=1&pageSize=20&version=1.21.1
# https://www.curseforge.com/minecraft/mc-mods/ftb-library-fabric/files/all?page=1&pageSize=20&version=1.21.1
# https://www.curseforge.com/minecraft/mc-mods/ftb-teams-fabric/files/all?page=1&pageSize=20&version=1.21.1
xaero_minimap_version=25.3.10
xaero_lib_version=1.1.0
xaero_mc_version=1.21.5
journeymap_version_fabric=1.21.1-6.0.0-beta.74+neoforge
journeymap_version_forge=1.21.1-6.0.0-beta.74+forge
journeymap_version_neoforge=1.21.1-6.0.0-beta.74+neoforge
journeymap_api_version=2.0.0-1.21.1-SNAPSHOT
common_network_version=1.0.21-1.21.1
architectury_version=13.0.8
map_atlases_version_forge=1.21-6.5.0-neoforge
map_atlases_version_neoforge=1.21-6.5.0-neoforge
map_atlases_version_fabric=1.21-6.5.0-fabric
moonlight_version_forge=1.21-2.29.16-neoforge
moonlight_version_neoforge=1.21-2.29.33-neoforge
moonlight_version_fabric=1.21-2.29.33-fabric
ftb_library_version=2101.1.31
ftb_teams_version=2101.1.10
ftb_chunks_version=2101.1.14

#Curios/Trinkets/Accessories
# https://modrinth.com/mod/curios/versions?g=1.21.1&l=neoforge
# https://modrinth.com/mod/trinkets/versions?g=1.21.1&l=fabric
# https://modrinth.com/mod/accessories/versions?g=1.21.1&l=fabric
# https://modrinth.com/mod/owo-lib/versions?g=1.21.1
curios_version=9.5.1+1.21.1
trinkets_version=3.10.0
accessories_version=1.1.0-beta.52+1.21.1
owo_version=0.12.15.4+1.21
owo_version_neoforge=0.12.15.1-beta.6+1.21
endec_version=0.1.8
endec_gson_version=0.1.5
endec_jankson_version=0.1.3.1
endec_netty_version=0.1.4

# Development QOL
# Mod Menu - https://modrinth.com/mod/modmenu/versions?g=1.21.1&l=fabric
# LazyDFU - https://modrinth.com/mod/lazydfu/versions?g=1.21.1&l=fabric
# Cloth Config - https://modrinth.com/mod/cloth-config/versions?g=1.21.1&l=fabric
cardinal_components_version=6.0.0
modmenu_version=11.0.4
lazydfu_version=
cloth_config_version=15.0.140
devauth_version=1.2.2
sodium_version_fabric=mc1.21.1-0.8.12-alpha.3-fabric
sodium_version_neoforge=mc1.21.1-0.8.12-alpha.2-neoforge

# NeoForge Options: serene, terra, ecliptic, homeostatic, protomanlys
# Forge Options: serene, terra, ecliptic
# Fabric Options: serene, fabric, fabric+extra, homeostatic
season_mod_neoforge=serene
season_mod_forge=ecliptic
season_mod_fabric=serene

# Dev minimap mod
# Options: xaero, journey, ftb, atlas, none
minimap_mod=none

# Dev accessory mod
# Options: accessories, none
accessory_mod=none
