plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
    //id 'net.minecraftforge.jarjar'
}

base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

minecraft {
    //mappings channel: 'official', version: minecraft_version
    mappings channel: "parchment", version: "${parchment_version}-${parchment_minecraft}"

    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        configureEach {
            // Mixin requires either specifying the config via command line, or in the Manifest
            args "--mixin.config=${mod_id}.mixins.json"
        }

        client {
            var clientDir = "run/client"
            if (!file(clientDir).exists()) {
                mkdir(clientDir)
            }
            systemProperty 'forge.enabledGameTestNamespaces', mod_id

            workingDir = file(clientDir)
        }

        server {
            var serverDir = "run/server"
            if (!file(serverDir).exists()) {
                mkdir(serverDir)
            }

            systemProperty 'forge.enabledGameTestNamespaces', mod_id

            workingDir = file(serverDir)
            args '--nogui'
        }

        data {
            var dataDir = "run/data"
            if (!file(dataDir).exists()) {
                mkdir(dataDir)
            }

            workingDir = file(dataDir)

            args '--mod', mod_id, '--all', '--output', layout.projectDirectory.dir('src/generated/resources'), '--existing', layout.projectDirectory.dir('src/main/resources')
        }
    }
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir layout.projectDirectory.dir('src/generated/resources') }

repositories {
    minecraft.mavenizer(repositories)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

repositories {
    maven {
        url = uri("https://repo.spongepowered.org/maven")
    }

    maven {
        name = 'Forge'
        url = uri('https://maven.minecraftforge.net/')
        content {
            includeGroup "net.minecraftforge"
        }
    }


    maven {
        name = "CurseMaven"
        url = uri("https://cursemaven.com")

        content {
            includeGroup "curse.maven"
        }
    }


    maven {
        name = "Modrinth Maven"
        url = uri("https://api.modrinth.com/maven")

        content {
            includeGroup "maven.modrinth"
        }
    }

    maven {
        name = "Forge Config API Port Maven"
        url = uri("https://raw.githubusercontent.com/Fuzss/modresources/main/maven/")
        content {
            includeGroup "fuzs.forgeconfigapiport"
        }
    }

    maven {
        name = "DevAuth Maven"
        url = uri("https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1")
        content {
            includeGroup "me.djtheredstoner"
        }
    }

    maven {
        name = 'Serene Seasons'
        url = uri('https://maven.minecraftforge.net/releases')
        content {
            includeGroup "com.github.glitchfiend"
        }
    }

    maven {
        name = "FTB Maven"
        url = uri("https://maven.ftb.dev/releases")
        content {
            includeGroup "dev.ftb.mods"
        }
    }

    maven {
        name = "shedaniel Maven"
        url = uri("https://maven.shedaniel.me/")
        content {
            includeGroup "me.shedaniel"
            includeGroup "dev.architectury"
            includeGroup "me.shedaniel.cloth"
        }
    }

    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
            includeGroup "info.journeymap"
        }
    }

    maven {
        name = "Xaero Maven"
        url = uri("https://chocolateminecraft.com/maven")
        content {
            includeGroup "xaero.lib"
            includeGroup "xaero.minimap"
        }
    }

//    maven {
//        name = "Journeymap API MAven"
//        url = uri("https://jm.gserv.me/repository/maven-public/")
//        content {
//            includeGroup "info.journeymap"
//        }
//    }

    maven {
        name = "Homeostatic Seasons"
        url = uri("https://raw.githubusercontent.com/wendall911/maven/main/")
        content {
            includeGroup "com.github.wendall911.climatesettings"
            includeGroup "com.github.wendall911.homeostaticseasons"
            includeGroup "technology.roughness.whitenoise"
        }
    }

    maven {
        name = "Accessories Maven"
        url = uri("https://maven.wispforest.io/releases")
        content {
            includeGroup "io.wispforest"
            includeGroup "io.wispforest.endec"
        }
    }

    maven {
        name = "Sinytra Maven"
        url = uri("https://maven.su5ed.dev/releases")
    }

    maven {
        name = "ModMaven (Backup)"
        url = uri("https://modmaven.dev/")
    }

    maven {
        name = "Curios Maven"
        url = uri("https://maven.theillusivec4.top/")
    }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${forge_version}")
    // Forge 1.21.6+ uses EventBus 7, which shifts most of its runtime validation to compile-time via an annotation processor
    // to improve performance in production environments. This line is required to enable said compile-time validation
    // in your development environment, helping you catch issues early.
    //annotationProcessor 'net.minecraftforge:eventbus-validator:7.0-beta.10'

    compileOnly "com.demonwav.mcdev:annotations:2.1.0"
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${project.mixin_extras_version}"))

    // Forge Config API Port
    compileOnlyApi "fuzs.forgeconfigapiport:forgeconfigapiport-forge:${project.forge_config_api_port_version}"
    implementation("maven.modrinth:forge-config-api-port:v${project.forge_config_api_port_version}-${project.minecraft_version}-Forge") {
        exclude group: 'net.fabricmc', module: 'fabric-loader'
    }

    // Serene Seasons
    compileOnly "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
    compileOnly "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"

    // Terrafirmacraft
    compileOnly "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
    compileOnly "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"
    compileOnly "maven.modrinth:barrels-2012:${project.barrels_version}"

    // Ecliptic Seasons
    compileOnly "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"

    // Homeostatic Seasons
    compileOnly "com.github.wendall911.climatesettings:climatesettings-${project.minecraft_version}-neoforge:${project.climatesettings_version}"
    compileOnly "com.github.wendall911.homeostaticseasons:homeostaticseasons-${project.minecraft_version}-neoforge:${project.homeostatic_seasons_version}"
    compileOnly "technology.roughness.whitenoise:whitenoise-${project.minecraft_version}-neoforge:${project.whitenoise_version}"

    // Xaero's Minimap
    compileOnly "xaero.minimap:xaerominimap-forge-${project.minecraft_version}:${project.xaero_minimap_version}"
    compileOnly "xaero.lib:xaerolib-forge-${project.minecraft_version}:${project.xaero_lib_version}"

    // JourneyMap
    compileOnly("info.journeymap:journeymap-api-forge:${project.journeymap_api_version}") {
        changing = true
    }
    compileOnly "maven.modrinth:journeymap:${project.journeymap_version_forge}"

    // FTB Chunks + Dependencies
    compileOnly "dev.ftb.mods:ftb-library-neoforge:${project.ftb_library_version}"
    compileOnly "dev.ftb.mods:ftb-teams-neoforge:${project.ftb_teams_version}"
    compileOnly "dev.ftb.mods:ftb-chunks-neoforge:${project.ftb_chunks_version}"
    compileOnly "dev.architectury:architectury-neoforge:${project.architectury_version}"

    // Map Atlases
    compileOnly "maven.modrinth:map-atlases-forge:${project.map_atlases_version_neoforge}"
    compileOnly "maven.modrinth:moonlight:${project.moonlight_version_neoforge}"

    // Curios
    compileOnly "top.theillusivec4.curios:curios-neoforge:${project.curios_version}"
    compileOnlyApi "top.theillusivec4.curios:curios-neoforge:${project.curios_version}:api"

    // Accessories
    compileOnly("io.wispforest:accessories-neoforge:${project.accessories_version}")
    compileOnly("me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_config_version}") {
        exclude(group: "net.fabricmc.fabric-api")
    }

    // Development QOL
    implementation("me.djtheredstoner:DevAuth-forge-latest:${devauth_version}")

    // Minimap Mod Dev Tests
    // See root gradle.properties to choose which to use at runtime.
    switch (project.minimap_mod.toLowerCase(Locale.ROOT)) {
        case "xaero":
            implementation "xaero.minimap:xaerominimap-forge-${project.minecraft_version}:${project.xaero_minimap_version}"
            implementation "xaero.lib:xaerolib-forge-${project.minecraft_version}:${project.xaero_lib_version}"
            break
        case "journey":
            implementation("info.journeymap:journeymap-api-forge:${project.journeymap_api_version}-SNAPSHOT") {
                changing = true
            }
            implementation "maven.modrinth:journeymap:${project.journeymap_version_forge}"
            implementation("maven.modrinth:common-network:${project.common_network_version}-forge")
            break
        case "ftb":
            break
        case "atlas":
            break
        case "none":
            break
        default:
            println("Unknown minimap mod specified: ${project.minimap_mod}. Must be xaero, journey, ftb, atlas, or none")
            break
    }

    // Season Mod Dev Tests (Forge)
    // See root gradle.properties to choose which to use at runtime.
    switch (project.season_mod_forge.toLowerCase(Locale.ROOT)) {
        case "serene":
            implementation "com.github.glitchfiend:SereneSeasons-forge:${project.serene_seasons_version}"
            implementation "com.github.glitchfiend:GlitchCore-forge:${project.glitchcore_version}"
            //implementation("net.jodah:typetools:0.6.3")
            break
        case "terra":
            implementation "maven.modrinth:terrafirmacraft:${project.terrafirmacraft_version}"
            implementation "maven.modrinth:patchouli:${project.patchouli_version}-neoforge"
            //implementation "maven.modrinth:curios:${project.curios_version}"
            implementation "maven.modrinth:barrels-2012:${project.barrels_version}"
            break
        case "ecliptic":
            implementation "curse.maven:ecliptic-seasons-1118306:${project.ecliptic_seasons_version}"
            break
        default:
            println("Unknown season mod specified: ${project.season_mod_forge}. Must be serene, terra, or ecliptic")
            break
    }
}


tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

tasks.named('jar', Jar) {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json"
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
        }
    }
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

publishMods {
    displayName = "${mod_id}-forge-${minecraft_version}-${mod_version}"
    version = "${minecraft_version}-${mod_version}"
    file = tasks.jar.archiveFile
    modLoaders.add("forge")

    def cfOptions = curseforgeOptions {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        changelogType = "markdown"
        javaVersions.add(JavaVersion.toVersion(project.java_version))
        minecraftVersions.addAll(curseforge_gameVersions.split(","))
        projectId = project.curseforge_forge_id
    }

    def mrOptions = modrinthOptions {
        accessToken = System.getenv("MODRINTH_TOKEN")
        minecraftVersions.addAll(modrinth_gameVersions.split(","))
        projectId = project.modrinth_forge_id
    }

    curseforge("curseforgeForge") {
        from cfOptions

        requires("forge-config-api-port")
        optional("serene-seasons")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair-play-edition", "map-atlases-forge")
    }

    modrinth("modrinthForge") {
        from mrOptions

        requires("forge-config-api-port")
        optional("serene-seasons")
        optional("journeymap", "xaeros-minimap", "xaeros-minimap-fair", "map-atlases-forge")
    }
}